services:
  postgres:
    image: postgres:17
    container_name: research-tracker-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: research_tracker_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: